services:
  - type: web
    name: lostfound
    env: docker
    repo: https://github.com/adityyyxx/lostfound.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
      value: 57041
