{
  "build": {
    "env": {
      "JAVA_VERSION": "17"
    },
    "command": "./mvnw package"
  },
  "start": {
    "command": "java -jar target/*.jar"
  }
}

    buildFilter:
    paths:
    - lostfound/lostfound/**

