services:
  - type: web
    name: lostfound
    env: docker
    repo: https://github.com/adityyyxx/lostfound.git
    branch: main
    dockerfilePath: lostfound/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 57014
      - key: DB_HOST
        value: dpg-d2bvhovdiees73f5c8qg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: admin_d06t
      - key: DB_USER
        value: aditya
      - key: DB_PASSWORD
        value: 8fS8zPr7Wg15RxAqULL9EsOWdcW2RvZ0
