services:
  - type: web
    name: springboot-app
    runtime: java
    repo: https://github.com/adityyyxx/lostfound.git
    branch: main
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/lostfound-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 57041
