services:
  - type: web
    name: lostfound
    env: java
    repo: https://github.com/adityyyxx/lostfound.git
    branch: main
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/lostfound-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: PORT
        value: 57014
